version: '3'
services:
  app:
    build: .
    command: /bin/bash -c 'bundle exec rake db:migrate && rails server'
    ports:
      - "3000:3000"
    environment:
      PGHOST: pg-db
      PGUSER: sample_postgres_user
      PGPASSWORD: sample_postgres_password
      PGDATABASE: postgres
      RAILS_ENV: development
    depends_on:
      - pg-db
  pg-db:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: sample_postgres_user
      POSTGRES_PASSWORD: sample_postgres_password
      POSTGRES_DATABASE: postgres
