default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PGDATABASE'] %>
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
